### ISSUE TITLE
[request]: Import python module located outside datafy project

### ISSUE THREAD

**Issue by tmszk** [datamindedbe/conveyor-roadmap#29]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
In our GIT repo we have multiple datafy projects. For the _on_failure_callback_ in each DAG we call a customized function. We want to be able to re-use this function across all datafy projects instead of copy-pasting it into each project. 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I can only import Python libs within the same project.
I would like to import an external module or package, like the solutions described here:
https://airflow.apache.org/docs/apache-airflow/stable/modules_management.html#packages-loading-in-python

**Are you currently working around this issue?**
Copy-pasting the function into each project.

**Comment by stijndehaes** [comment]
Thank you for submitting this issue!
At the moment you can import functions from other projects, for example you can make a utility project and use functions from that in other projects, the pattern is described here: https://docs.datafy.cloud/how-to-guides/airflow/common-project-with-airflow-utilities

We do realise this is not a perfect solution because you always have to deploy both projects but it at least makes it a bit easier then copy pasting function everywhere. Let me know if this can already help you.

Also we are thinking of pattern where a platform team could add extra functionality to airflow that can be used by multiple teams, this problem might fall into that catagory but we don't have a timeline on when we would start working on this.

**Comment by tmszk** [comment]
Hi Stijn, thanks for the feedback! We successfully implemented this pattern and it is sufficient for our use case.

As you mentioned there are some drawbacks (a.o. no dag validation unless extra code when importing common code) but this is not really an issue for us, as the common code is not expected to change frequently.

**Comment by vlieven** [comment]
Hi @tmszk, we've recently improved the support for Airflow dependencies between different projects. You can refer to this documentation page: https://docs.conveyordata.com/how-to-guides/working-with-airflow/conveyor-build-shared-code/

This should allow you to run dag-validation as well as `conveyor run` commands.
