### ISSUE TITLE
[request]: Download button for Datafy logs

### ISSUE THREAD

**Issue by dadadima** [datamindedbe/conveyor-roadmap#31]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Download button for Datafy logs**
It would be useful to have the option to download the Datafy logs as .txt or something.

Currently, it's a bit hard and not friendly at all to explore long logs via the Datafy UI. The filtering also doesn't work so well. Same for the Older/Newer Log button. I am not saying they do not work at all, but It's all a bit clanky and often to get to the page/section you need you have to play with the tool for some time.

So, I was thinking that one way to solve this for huge log messages is giving us the possibility to download it as .txt and let the user read the logs in a text editor locally.

**Comment by stijndehaes** [comment]
So if I understand this correctly you are looking for a better way to search through the logs? One option is allowing you to download the logs.
Would a better search functionality also work for you?

Also are you mostly looking at spark logs or something else?

**Comment by dadadima94** [comment]
That's correct. Downloading and a better search are both good option and I see them as independent and not exclusive. 
It's not really clear what log pages are (since they have variable length). It's also not clear why the refresh button does and how that impacts the pages. Also the pages seem to be inconsistent if you access logs multiple times. Maybe the classic buttons at the bottom < 1, 2, 3, .. .. .. ..  11, 12>  <next> <previous> <last> <first> would be also useful.

**Comment by pascal-knapen** [comment]
Added this button to download the logs: 
![image](https://github.com/user-attachments/assets/74b61fa4-c26f-4ec5-968a-10e290ce306f)
